name: nobox_mobile
description: Nobox mobile application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^10.2.4
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  webview_flutter: ^4.13.0    
  image_picker: ^1.0.7        
  device_info_plus: ^9.1.0
  permission_handler: ^11.3.0
  mime: ^1.0.4                 
  path: ^1.8.3 
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.3
  intl: ^0.20.2
  http_parser: ^4.0.2
  video_player: ^2.7.0
  path_provider: ^2.1.1
  gal: ^2.3.0
  share_plus: ^7.2.1
  dio: ^5.3.3
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/nobox2.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/nobox2.png
    - assets/nobox.png